Repository alcohol-king/yellowcard-api, pull requests merged in 2018-12, with the labels that each got.

#4 [FIX] #3 DB 스키마 수정
  src/main/resources/db.migration/V0_0_1__init.sql
Labels: invalid

#5 WIP Feature/#1 jpa h2 settings
  .idea/compiler.xml
  .idea/modules.xml
  src/main/java/com/depromeet/yellowcardapi/user/domain/User.java
  src/main/java/com/depromeet/yellowcardapi/user/domain/UserRepository.java
  src/main/resources/db.migration/V0_0_1__init.sql
  src/test/java/com/depromeet/yellowcardapi/JpaTests.java
Labels: enhancement

#10 close #7
  .idea/compiler.xml
  .idea/modules.xml
  .idea/modules/yellowcard-api_main.iml
  .idea/modules/yellowcard-api_test.iml
  build.gradle
  src/main/java/com/depromeet/yellowcardapi/config/AppConfig.java
  src/main/java/com/depromeet/yellowcardapi/config/JwtAuthenticationFilter.java
  src/main/java/com/depromeet/yellowcardapi/config/WebSecurityConfig.java
  src/main/java/com/depromeet/yellowcardapi/controller/SignInController.java
  src/main/java/com/depromeet/yellowcardapi/domain/User.java
  src/main/java/com/depromeet/yellowcardapi/domain/UserRepository.java
  src/main/java/com/depromeet/yellowcardapi/dto/KakaoUserMeResponse.java
  src/main/java/com/depromeet/yellowcardapi/dto/SignInRequest.java
  src/main/java/com/depromeet/yellowcardapi/dto/SignInResponse.java
  src/main/java/com/depromeet/yellowcardapi/exception/InvalidTokenException.java
  src/main/java/com/depromeet/yellowcardapi/exception/KakaoAuthenticationFailedException.java
  src/main/java/com/depromeet/yellowcardapi/exception/UserNotFoundException.java
  src/main/java/com/depromeet/yellowcardapi/service/JwtTokenProvider.java
  src/main/java/com/depromeet/yellowcardapi/service/KakaoSignInService.java
  src/main/java/com/depromeet/yellowcardapi/service/SignInService.java
  src/main/java/com/depromeet/yellowcardapi/service/UserDetailsServiceImpl.java
  src/main/java/com/depromeet/yellowcardapi/test/TestController.java
Labels: enhancement

#13 close #12 drink type 변수 enum으로 변경
  .idea/.name
  src/main/java/com/depromeet/yellowcardapi/domain/Drink.java
  src/main/java/com/depromeet/yellowcardapi/domain/DrinkType.java
  src/main/java/com/depromeet/yellowcardapi/dto/DrinkRequest.java
  src/main/java/com/depromeet/yellowcardapi/dto/DrinkResponse.java
Labels: suggestion

#15 close #14 API parameter key 이름 snake case로 변경
  src/main/java/com/depromeet/yellowcardapi/dto/DrinkRequest.java
  src/main/java/com/depromeet/yellowcardapi/dto/DrinkResponse.java
Labels: suggestion

#19 close #18 user_drink 테이블 이름 drink_card로 변경
  src/main/resources/db.migration/V0_0_1__init.sql
Labels: suggestion

#23 close #20 drink_history 컬럼 내용 변경
  src/main/resources/db.migration/V0_0_1__init.sql
Labels: suggestion

#38 close #21 메인 화면 데이터 조회 API 추가
  src/main/java/com/depromeet/yellowcardapi/controller/MainController.java
  src/main/java/com/depromeet/yellowcardapi/domain/DrinkCard.java
  src/main/java/com/depromeet/yellowcardapi/domain/DrinkCardRepository.java
  src/main/java/com/depromeet/yellowcardapi/domain/User.java
  src/main/java/com/depromeet/yellowcardapi/dto/DrinkCardResponse.java
  src/main/java/com/depromeet/yellowcardapi/dto/MainResponse.java
  src/main/java/com/depromeet/yellowcardapi/service/MainService.java
  src/main/java/com/depromeet/yellowcardapi/service/MainServiceImpl.java
  src/main/resources/db.migration/V0_0_2__add_drink_card_message.sql
  src/test/java/com/depromeet/yellowcardapi/MainServiceTests.java
Labels: enhancement

#32 close #31 flyway 설정
  build.gradle
  src/main/java/com/depromeet/yellowcardapi/domain/Drink.java
  src/main/java/com/depromeet/yellowcardapi/domain/DrinkHistory.java
  src/main/java/com/depromeet/yellowcardapi/domain/User.java
  src/main/java/com/depromeet/yellowcardapi/dto/DrinkRequest.java
  src/main/java/com/depromeet/yellowcardapi/dto/DrinkResponse.java
  src/main/resources/db/migration/V0_0_1__init.sql
Labels: enhancement
